language: node_js
node_js:
  - 17  # initially 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Use either `docker-compose` or individual `docker build` commands for every file
  # Build
  - docker-compose -f docker-compose-build.yaml build --parallel # or repeat and use docker build -t udagram-api-feed ./udagram-api-feed
  # Do similar for other three images
  - docker tag udagram-api-feed xtrahuman/udagram-api-feed:v1
  - docker tag udagram-api-user xtrahuman/udagram-api-user:v1
  - docker tag reverseproxy xtrahuman/reverseproxy:v1
  - docker tag udagram-frontend xtrahuman/udagram-frontend:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xtrahuman/udagram-api-feed:v1
  - docker push xtrahuman/udagram-api-user:v1
  - docker push xtrahuman/reverseproxy:v1
  - docker push xtrahuman/udagram-frontend:v1