apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: reverseproxy
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: reverseproxy
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: frontend
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: frontend
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend-feed
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend-feed
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend-user
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend-user
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50