apiVersion: v1
kind: Service
metadata:
  labels:
    run: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: reverseproxy