apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: xtrahuman/udagram-reverseproxy:v2
        imagePullPolicy: Always          
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: docker_username
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: docker_password
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_username
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_password
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_access_key_id
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_session_token
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"    
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: jwt_secret
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: data-config
                key: postgres_host
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: data-config
                key: postgres_db
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: data-config
                key: aws_bucket
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: data-config
                key: aws_region
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: data-config
                key: aws_profile
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
        ports:
        - containerPort: 8080
    # restartPolicy: Never