name: docker-push

on:
  push:
    branches: [ main ]
    paths: .github/workflows/docker-push.yml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-deploy-microservice:
    environment:
      name: docker
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: xtrahuman # name of Docker Hub ID
      # IMAGE_NAME: webapp
      # IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:

      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Build Docker Image
        run:
          docker-compose -f docker-compose-build.yaml build --parallel # or repeat and use docker build -t udagram-api-feed ./udagram-api-feed
          docker tag udagram-api-feed xtrahuman/udagram-api-feed:v1
          docker tag udagram-api-user xtrahuman/udagram-api-user:v1
          docker tag reverseproxy xtrahuman/reverseproxy:v1
          docker tag udagram-frontend xtrahuman/udagram-frontend:v1

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   continue-on-error: true
      #   with:
      #     image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
      - name: Push Image to Docker Hub
        run:
        docker push xtrahuman/udagram-api-feed:v1
        docker push xtrahuman/udagram-api-user:v1
        docker push xtrahuman/reverseproxy:v1
        docker push xtrahuman/udagram-frontend:v1